on: 
 push:
  branches:
      - 'main'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: kanadgupta/glitch-sync@main
      with:
        auth-token: '${{ secrets.AUTH_TOKEN }}'
        project-id: '${{ secrets.PROJECT_ID }}'
        # path: 'dist' # optional
